### ISSUE TITLE
Any code run in Playground fails with same error

### ISSUE THREAD

**Issue by nkrisc** [skpm/sketch-dev-tools#46] opened 2019-05-01 14:07 UTC
**Environment**
Plugin v0.9.4
Sketch v54.1
macOS v10.14.4

**Issue**
Running _any_ code in the Playground tab of the plugin causes the same error. So far I have yet to see any other result. 
For example, the default `console.log(context)` or even simply `'a'`.
The following error is always displayed when any code is run:

```
TypeError: null is not an object (evaluating 'e.navigationDelegate().valueForKey("state").wasReady')
i show-debugger.js:115:308
show-debugger.js:211:3693
emit index.js:146:17
emit show-debugger.js:139:2589
userContentController:didReceiveScriptMessage: show-debugger.js:139:2241
```

This same error is also present in the console when first opening the plugin.

**Comment by mathieudutour** [comment] 2019-05-01 14:49
Ah yes, can you try v0.9.5?

**Comment by nkrisc** [comment] 2019-05-01 16:12
I've downloaded v0.9.5 and the initial issue I described seems to be resolved. However, instead, any code in the playground results in the following object being logged:

```
Object
line: 1
sourceURL: user-script:6
column: 74
```
Sometimes `sourceURL` is `user-script:2` depending on what I enter. I can't discern a pattern.

**Comment by mathieudutour** [comment] 2019-05-01 19:35
I'm not able to reproduce 🤔

**Comment by nkrisc** [comment] 2019-05-01 19:41
Remarkably, I just went to check again to see if I could glean more info about the issue and it appears to be working. I had restarted Sketch again just to be sure, but looks good. I'll poke around more to be sure but looks like the last update might have solved the issue after all. 

What is strange though is the issue I referenced in my last comment is something I had seen when using v0.9.3.

**Comment by mathieudutour** [comment] 2019-05-01 19:43
Maybe it's a specific piece of code?

I'm going to close this but feel free to open another one if you can reproduce it

**Closed as completed by mathieudutour** 2019-05-01 19:43 UTC
Labels: bug
